bia_pipeline:
  outputs:
    dev:
      dataset: campaign
      job_execution_timeout_seconds: 300
      job_retries: 1
      # keyfile: /Users/kapoord/Documents/dbt_bia_etl/dbt_bia_pipeline/service_key.json
      keyfile: /etl/dbt_permission.json
      location: US
      method: service-account
      priority: interactive
      project: dbt-pipeline-415806
      threads: 1
      type: bigquery
  target: dev